!obj:pylearn2.train.Train {
    # Dataset for training
    dataset: &train !obj:pylearn2ext.epilepsiae.EpilepsiaeTest {
        patient_id: %(patient_id)i,
        which_set: 'train',
        preprocessor_path: '%(save_path)s/sdae_scaler.pkl',
        data_dir: '%(data_path)s',
        leave_one_out_seizure: %(leave_one_out_seizure)i,
        sample_size_second: 1,
        batch_size: %(batch_size)i
    },
    # Model to be trained
    model: !obj:pylearn2.models.autoencoder.Autoencoder {
        nvis : 256,
        nhid : %(nhid)i,
        irange : 0.05,
        act_enc: "sigmoid",
        act_dec: "sigmoid",
    },
    # Training algorithm
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate : 1e-3,
        batch_size : %(batch_size)i,
        monitoring_batches : %(monitoring_batches)i,
        monitoring_dataset : *train,
        cost : !obj:pylearn2.costs.cost.SumOfCosts {
            costs: [
               !obj:pylearn2.costs.autoencoder.MeanSquaredReconstructionError {},
               !obj:pylearn2ext.autoencoder.WeightDecay {
                  coeff: 3e-3
               },
               !obj:pylearn2.costs.autoencoder.SparseActivation {
                  coeff: 3,
                  p: 0.1
               }
             ]
        },
        termination_criterion : !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: %(max_epochs)i,
        },
    },
    save_path: "%(save_path)s/sdae_l1.pkl",
    save_freq: 1
}
